### ISSUE TITLE
RuntimeError: Expected 3-dimensional

### ISSUE THREAD

**Issue by NolenBrolen** [ali-vilab/dreamtalk#25]
I tried to install it locally on WSL to test out dreamtalk, but when I try to run 'inference_for_demo_video.py' then I get the following error:

`Traceback (most recent call last):
  File "inference_for_demo_video.py", line 198, in <module>
    inputs.input_values.to(device), return_dict=False
  File "/home/USER/miniconda3/envs/dreamtalk/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/USER/miniconda3/envs/dreamtalk/lib/python3.7/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 1306, in forward
    extract_features = self.feature_extractor(input_values)
  File "/home/USER/miniconda3/envs/dreamtalk/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/USER/miniconda3/envs/dreamtalk/lib/python3.7/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 453, in forward
    hidden_states = conv_layer(hidden_states)
  File "/home/USER/miniconda3/envs/dreamtalk/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/USER/miniconda3/envs/dreamtalk/lib/python3.7/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 325, in forward
    hidden_states = self.conv(hidden_states)
  File "/home/USER/miniconda3/envs/dreamtalk/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/USER/miniconda3/envs/dreamtalk/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 263, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/USER/miniconda3/envs/dreamtalk/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 260, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 3-dimensional input for 3-dimensional weight [512, 1, 10], but got 4-dimensional input of size [1, 1, 2, 732160] instead`

**Comment by Masoudvahid** [comment]
same issue
