### ISSUE TITLE
nvrtc compilation failed

### ISSUE THREAD

**Issue by StartHua** [ali-vilab/dreamtalk#3]
(dreamtalk) F:\AI\dreamtalk-main>python inference_for_demo_video.py --wav_path data/audio/acknowledgement_english.m4a --style_clip_path data/style_clip/3DMM/M030_front_neutral_level1_001.mat --pose_path data/pose/RichardShelby_front_neutral_level1_001.mat --image_path data/src_img/uncropped/male_face.png --cfg_scale 1.0 --max_gen_len 30 --output_name acknowledgement_english@M030_front_neutral_level1_001@male_face
D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'data/audio/acknowledgement_english.m4a':
  Metadata:
    major_brand     : M4A
    minor_version   : 0
    compatible_brands: M4A isommp42
    creation_time   : 2023-12-20T14:25:20.000000Z
    iTunSMPB        :  00000000 00000840 00000000 00000000000C23C0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
  Duration: 00:00:16.57, start: 0.044000, bitrate: 246 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 244 kb/s (default)
    Metadata:
      creation_time   : 2023-12-20T14:25:20.000000Z
      handler_name    : Core Media Audio
Stream mapping:
  Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
-async is forwarded to lavfi similarly to -af aresample=async=1:min_hard_comp=0.100000:first_pts=0.
Output #0, wav, to 'tmp/acknowledgement_english@M030_front_neutral_level1_001@male_face\acknowledgement_english@M030_front_neutral_level1_001@male_face_16K.wav':
  Metadata:
    major_brand     : M4A
    minor_version   : 0
    compatible_brands: M4A isommp42
    iTunSMPB        :  00000000 00000840 00000000 00000000000C23C0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    ISFT            : Lavf58.45.100
    Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s (default)
    Metadata:
      creation_time   : 2023-12-20T14:25:20.000000Z
      handler_name    : Core Media Audio
      encoder         : Lavc58.91.100 pcm_s16le
size=     518kB time=00:00:16.57 bitrate= 256.0kbits/s speed=1.02e+03x
video:0kB audio:518kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.014706%
Some weights of the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english were not used when initializing Wav2Vec2Model: ['lm_head.weight', 'lm_head.bias']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "inference_for_demo_video.py", line 211, in <module>
    max_audio_len=args.max_gen_len,
  File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "inference_for_demo_video.py", line 105, in inference_one_video
    ddim_num_step=ddim_num_step,
  File "F:\AI\dreamtalk-main\core\networks\diffusion_net.py", line 226, in sample
    ready_style_code=ready_style_code,
  File "F:\AI\dreamtalk-main\core\networks\diffusion_net.py", line 170, in ddim_sample
    x_t_double, t=t_tensor_double, **context_double
  File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\AI\dreamtalk-main\core\networks\diffusion_util.py", line 126, in forward
    style_code = self.style_encoder(style_clip, style_pad_mask)
  File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\AI\dreamtalk-main\core\networks\generator.py", line 193, in forward
    style_code = self.aggregate_method(permute_style, pad_mask)
  File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\AI\dreamtalk-main\core\networks\self_attention_pooling.py", line 31, in forward
    att_logits = self.W(batch_rep).squeeze(-1)
  File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
    input = module(input)
  File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\AI\dreamtalk-main\core\networks\mish.py", line 51, in forward
    return mish(input)
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

nvrtc compilation failed:

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_tanh_mul(float* t0, float* t1, float* aten_mul) {
{
  float v = __ldg(t0 + (((512 * blockIdx.x + threadIdx.x) / 65536) * 65536 + 256 * (((512 * blockIdx.x + threadIdx.x) / 256) % 256)) + (512 * blockIdx.x + threadIdx.x) % 256);
  float v_1 = __ldg(t1 + (((512 * blockIdx.x + threadIdx.x) / 65536) * 65536 + 256 * (((512 * blockIdx.x + threadIdx.x) / 256) % 256)) + (512 * blockIdx.x + threadIdx.x) % 256);
  aten_mul[(((512 * blockIdx.x + threadIdx.x) / 65536) * 65536 + 256 * (((512 * blockIdx.x + threadIdx.x) / 256) % 256)) + (512 * blockIdx.x + threadIdx.x) % 256] = v * (tanhf(v_1));
}
}

**Comment by auroraxs** [comment]
如果你是通过pip对Pytorch进行安装，会导致缺失libnvrtc-builtins.so.11.1这个文件，从而出现这个错误。

但并不需要重装torch、torchvision或者cuda，可以通过将torch的安装路径（比如我是用conda环境，路径就是anaconda3/envs/envs_name/lib/python3.7/site-packages/torch）下torch/lib中的“libnvrtc-builtins.so”文件命名为“libnvrtc-builtins.so.11.1”，注意后缀不是".so"变成了".so.11.1"。

**Comment by auroraxs** [comment]
> (dreamtalk) F:\AI\dreamtalk-main>python inference_for_demo_video.py --wav_path data/audio/acknowledgement_english.m4a --style_clip_path data/style_clip/3DMM/M030_front_neutral_level1_001.mat --pose_path data/pose/RichardShelby_front_neutral_level1_001.mat --image_path data/src_img/uncropped/male_face.png --cfg_scale 1.0 --max_gen_len 30 --output_name acknowledgement_english@M030_front_neutral_level1_001@male_face D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torchaudio\extension\extension.py:13: UserWarning: torchaudio C++ extension is not available. warnings.warn('torchaudio C++ extension is not available.') ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers built with gcc 10.2.1 (GCC) 20200726 configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf libavutil 56. 51.100 / 56. 51.100 libavcodec 58. 91.100 / 58. 91.100 libavformat 58. 45.100 / 58. 45.100 libavdevice 58. 10.100 / 58. 10.100 libavfilter 7. 85.100 / 7. 85.100 libswscale 5. 7.100 / 5. 7.100 libswresample 3. 7.100 / 3. 7.100 libpostproc 55. 7.100 / 55. 7.100 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'data/audio/acknowledgement_english.m4a': Metadata: major_brand : M4A minor_version : 0 compatible_brands: M4A isommp42 creation_time : 2023-12-20T14:25:20.000000Z iTunSMPB : 00000000 00000840 00000000 00000000000C23C0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 Duration: 00:00:16.57, start: 0.044000, bitrate: 246 kb/s Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 244 kb/s (default) Metadata: creation_time : 2023-12-20T14:25:20.000000Z handler_name : Core Media Audio Stream mapping: Stream #0:0 -> #0:0 (aac (native) -> pcm_s16le (native)) Press [q] to stop, [?] for help -async is forwarded to lavfi similarly to -af aresample=async=1:min_hard_comp=0.100000:first_pts=0. Output #0, wav, to 'tmp/acknowledgement_english@M030_front_neutral_level1_001@male_face\acknowledgement_english@[M030_front_neutral_level1_001@male_face_16K.wav](mailto:M030_front_neutral_level1_001@male_face_16K.wav)': Metadata: major_brand : M4A minor_version : 0 compatible_brands: M4A isommp42 iTunSMPB : 00000000 00000840 00000000 00000000000C23C0 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 ISFT : Lavf58.45.100 Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s (default) Metadata: creation_time : 2023-12-20T14:25:20.000000Z handler_name : Core Media Audio encoder : Lavc58.91.100 pcm_s16le size= 518kB time=00:00:16.57 bitrate= 256.0kbits/s speed=1.02e+03x video:0kB audio:518kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.014706% Some weights of the model checkpoint at jonatasgrosman/wav2vec2-large-xlsr-53-english were not used when initializing Wav2Vec2Model: ['lm_head.weight', 'lm_head.bias']
> 
> * This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> * This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
>   Traceback (most recent call last):
>   File "inference_for_demo_video.py", line 211, in 
>   max_audio_len=args.max_gen_len,
>   File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>   return func(*args, **kwargs)
>   File "inference_for_demo_video.py", line 105, in inference_one_video
>   ddim_num_step=ddim_num_step,
>   File "F:\AI\dreamtalk-main\core\networks\diffusion_net.py", line 226, in sample
>   ready_style_code=ready_style_code,
>   File "F:\AI\dreamtalk-main\core\networks\diffusion_net.py", line 170, in ddim_sample
>   x_t_double, t=t_tensor_double, **context_double
>   File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
>   result = self.forward(*input, **kwargs)
>   File "F:\AI\dreamtalk-main\core\networks\diffusion_util.py", line 126, in forward
>   style_code = self.style_encoder(style_clip, style_pad_mask)
>   File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
>   result = self.forward(*input, **kwargs)
>   File "F:\AI\dreamtalk-main\core\networks\generator.py", line 193, in forward
>   style_code = self.aggregate_method(permute_style, pad_mask)
>   File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
>   result = self.forward(*input, **kwargs)
>   File "F:\AI\dreamtalk-main\core\networks\self_attention_pooling.py", line 31, in forward
>   att_logits = self.W(batch_rep).squeeze(-1)
>   File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
>   result = self.forward(*input, **kwargs)
>   File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\container.py", line 119, in forward
>   input = module(input)
>   File "D:\python\Anaconda\envs\dreamtalk\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
>   result = self.forward(*input, **kwargs)
>   File "F:\AI\dreamtalk-main\core\networks\mish.py", line 51, in forward
>   return mish(input)
>   RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)
> 
> nvrtc compilation failed:
> 
> #define NAN __int_as_float(0x7fffffff) #define POS_INFINITY __int_as_float(0x7f800000) #define NEG_INFINITY __int_as_float(0xff800000)
> 
> template **device** T maximum(T a, T b) { return isnan(a) ? a : (a > b ? a : b); }
> 
> template **device** T minimum(T a, T b) { return isnan(a) ? a : (a < b ? a : b); }
> 
> extern "C" **global** void fused_tanh_mul(float* t0, float* t1, float* aten_mul) { { float v = __ldg(t0 + (((512 * blockIdx.x + threadIdx.x) / 65536) * 65536 + 256 * (((512 * blockIdx.x + threadIdx.x) / 256) % 256)) + (512 * blockIdx.x + threadIdx.x) % 256); float v_1 = __ldg(t1 + (((512 * blockIdx.x + threadIdx.x) / 65536) * 65536 + 256 * (((512 * blockIdx.x + threadIdx.x) / 256) % 256)) + (512 * blockIdx.x + threadIdx.x) % 256); aten_mul[(((512 * blockIdx.x + threadIdx.x) / 65536) * 65536 + 256 * (((512 * blockIdx.x + threadIdx.x) / 256) % 256)) + (512 * blockIdx.x + threadIdx.x) % 256] = v * (tanhf(v_1)); } }

如果你是通过pip对Pytorch进行安装，会导致缺失libnvrtc-builtins.so.11.1这个文件，从而出现这个错误。

但并不需要重装torch、torchvision或者cuda，可以通过将torch的安装路径（比如我是用conda环境，路径就是anaconda3/envs/envs_name/lib/python3.7/site-packages/torch）下torch/lib中的“libnvrtc-builtins.so”文件命名为“libnvrtc-builtins.so.11.1”，注意后缀不是".so"变成了".so.11.1"。

**Comment by hiowenluke** [comment]
@auroraxs:

In Windows, there is no libnvrtc-builtins.so file in folder torch/lib. :(

**Comment by hiowenluke** [comment]
@StartHua :

Did you solved this problem?

**Comment by b0b6a** [comment]
@auroraxs :     
I tried this method but it didn't work. Is there any other solution?
